ALTER TABLE inventory_item DROP CONSTRAINT IF EXISTS FK_INVENTORY_ITEM_ON_BOOK_STORE;
ALTER TABLE inventory_movement DROP CONSTRAINT IF EXISTS FK_INVENTORY_MOVEMENT_ON_BOOK_STORE;
ALTER TABLE sale DROP CONSTRAINT IF EXISTS FK_SALE_ON_BOOK_STORE;

ALTER TABLE inventory_item DROP COLUMN IF EXISTS book_store_id;
ALTER TABLE inventory_movement DROP COLUMN IF EXISTS book_store_id;
ALTER TABLE sale DROP COLUMN IF EXISTS book_store_id;

ALTER TABLE sale_item DROP COLUMN IF EXISTS discount_percent;

DROP TABLE IF EXISTS book_store CASCADE;
